apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  # labels:
  #   app: mysql
  #   project: roboshop
  #   tier: db
spec:
  selector:
    matchLabels:
      app: mysql
      project: roboshop
      tier: db
  serviceName: "mysql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers: 
      - name: mysql
        image: saikiranreddy11/mysql:1.0.0
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-sc"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql-port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # keep true in double quotes
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"