apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db
  serviceName: "mongodb"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: saikiranreddy11/mongodb:1.0.0
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-sc"
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: name-of-service-port